# Eval Assignment Example Analysis

This notebook shows how to produce the graphs in the assignment instructions.

## Setup

First, we need to import some Python packages.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Importing Data

Then we import the data.

In [2]:
df = pd.read_csv('build/eval-results.csv')
df = df.rename(columns=lambda x: x.replace('.', '_'))
df.head()

,Partition,Algorithm,NNbrs,Coverage,RMSE_ByUser,Predict_nDCG,TopN_nDCG,MRR,MAP,TagEntropy
0,1,GlobalMean,NaN,1.0,0.952068,0.942429,NaN,NaN,NaN,NaN
1,1,ItemMean,NaN,1.0,0.856958,0.963443,0.029508,0.059167,0.012486,7.567864
2,1,PersMean,NaN,1.0,0.758039,0.963443,0.029508,0.059167,0.012486,7.567864
3,1,Popular,NaN,0.0,NaN,NaN,0.092203,0.180894,0.043285,7.935712
4,1,UserUserCosine,5.0,1.0,0.784884,0.966245,0.018197,0.034219,0.007147,7.606174

## Example Plots

Now we can produce the basic plots.

First, we want to only deal with the baseline algorithms right now.

In [3]:
baselines = df[df.NNbrs.isnull()]
baselines

,Partition,Algorithm,NNbrs,Coverage,RMSE_ByUser,Predict_nDCG,TopN_nDCG,MRR,MAP,TagEntropy
0,1,GlobalMean,NaN,1.0,0.952068,0.942429,NaN,NaN,NaN,NaN
1,1,ItemMean,NaN,1.0,0.856958,0.963443,0.029508,0.059167,0.012486,7.567864
2,1,PersMean,NaN,1.0,0.758039,0.963443,0.029508,0.059167,0.012486,7.567864
3,1,Popular,NaN,0.0,NaN,NaN,0.092203,0.180894,0.043285,7.935712
44,2,GlobalMean,NaN,1.0,0.950236,0.937746,NaN,NaN,NaN,NaN
45,2,ItemMean,NaN,1.0,0.846915,0.965646,0.028784,0.056733,0.012097,7.570876
46,2,PersMean,NaN,1.0,0.747672,0.965646,0.028784,0.056733,0.012097,7.570876
47,2,Popular,NaN,0.0,NaN,NaN,0.092300,0.176380,0.045563,7.925914
88,3,GlobalMean,NaN,1.0,0.921363,0.941724,NaN,NaN,NaN,NaN
89,3,ItemMean,NaN,1.0,0.825229,0.966515,0.027766,0.052415,0.011314,7.594121
90,3,PersMean,NaN,1.0,0.733503,0.966515,0.027766,0.052415,0.011314,7.594121
91,3,Popular,NaN,0.0,NaN,NaN,0.093622,0.183791,0.046450,7.929304
132,4,GlobalMean,NaN,1.0,0.962079,0.942893,NaN,NaN,NaN,NaN
133,4,ItemMean,NaN,1.0,0.857405,0.965031,0.025915,0.056476,0.011709,7.483256
134,4,PersMean,NaN,1.0,0.766456,0.965031,0.025915,0.056476,0.011709,7.483256
135,4,Popular,NaN,0.0,NaN,NaN,0.090601,0.170818,0.043749,7.923547
176,5,GlobalMean,NaN,1.0,0.951087,0.939974,NaN,NaN,NaN,NaN
177,5,ItemMean,NaN,1.0,0.855981,0.966349,0.024330,0.044185,0.009204,7.548965
178,5,PersMean,NaN,1.0,0.769087,0.966349,0.024330,0.044185,0.009204,7.548965
179,5,Popular,NaN,0.0,NaN,NaN,0.094547,0.191203,0.045860,7.928965

Then we can plot RMSE:

In [7]:
const_rmse = baselines.pivot(index='Partition', columns='Algorithm', values='RMSE_ByUser')
const_rmse.plot(kind='box')

Now we can do top-N nDCG:

In [5]:
baselines.pivot(index='Partition', columns='Algorithm', values='TopN_nDCG').plot(kind='box')

And Predict nDCG:

In [6]:
baselines.pivot(index='Partition', columns='Algorithm', values='Predict_nDCG').plot(kind='box')